mod 'puppet-cron', '2.0.0'
mod 'puppetlabs-vcsrepo', '5.0.0'
mod 'puppet-splunk', '8.0.0'
mod 'puppetlabs-concat', '4.2.1'
mod 'puppetlabs-inifile', '1.4.1'
mod 'puppetlabs-stdlib', '4.25.0'
mod 'puppet-archive', '2.0.0'
